name: Deploy Flory's to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify secrets
      run: |
        echo "FTP Server: ${{ secrets.HOSTINGER_FTP_SERVER }}"
        echo "FTP Username: ${{ secrets.HOSTINGER_FTP_USERNAME }}"
        echo "FTP Port: ${{ secrets.HOSTINGER_FTP_PORT || 21 }}"

    - name: List local directory
      run: ls -R ./

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.HOSTINGER_FTP_SERVER }}
        username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        port: ${{ secrets.HOSTINGER_FTP_PORT || 21 }}
        local-dir: ./
        server-dir: /public_html
        exclude: |
          .git*
          node_modules/
          tests/
          vendor/
          .env
          storage/
          .github/