name: Deploy Laravel Project to Hostinger

on:
  push:
    branches:
      - main # Se activa en cada push a la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout el código de la rama actual
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar SSH usando el Secret
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Paso 3: Conectar al servidor y desplegar
      - name: Deploy to Hostinger
        run: |
          ssh -o StrictHostKeyChecking=no  -p 65002 u348037785@178.16.128.34 "
            cd public_html/ &&
            git pull origin main &&
            php -d memory_limit=-1 /usr/local/bin/composer1.phar update --no-dev &&
            php artisan cache:clear
          "
