name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to Hostinger
        env:
          HOSTINGER_PASS: ${{ secrets.HOSTINGER_PASS }}
        run: |
          sshpass -p "${{ secrets.HOSTINGER_PASS }}" ssh -o StrictHostKeyChecking=no -p 65002 u348037785@178.16.128.34 "rsync -avz --delete-after /path/to/local/project/ /home/u348037785/public_html/"
