name: Deploy Laravel to Hostinger via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: ${{ secrets.HOSTINGER_FTP_SERVER }}
        username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        local-dir: ./
        server-dir: /public_html
        exclude: |
          .git*
          node_modules/
          tests/
          vendor/
          .env
          storage/
          .github/
        exclude-older: true

    - name: Upload Vendor Folder
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: ${{ secrets.HOSTINGER_FTP_SERVER }}
        username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        local-dir: ./vendor
        server-dir: /public_html/vendor
        exclude-older: true

    - name: Upload Storage Folder
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: ${{ secrets.HOSTINGER_FTP_SERVER }}
        username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        local-dir: ./storage
        server-dir: /public_html/storage
        exclude-older: true